name: Register Microservice Deployment

on:
  push:
    branches:
      - test
    paths:
      - 'register-microservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd register-microservice
        npm install

    - name: Run Tests
      run: |
        cd register-microservice
        npm test

    - name: Build Docker Image
      run: |
        cd register-microservice
        docker build -t register-microservice .

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag register-microservice myrepo/register-microservice:latest
        docker push myrepo/register-microservice:latest
