name: Reset Password Microservice CI/CD

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t reset-password-microservice .

    - name: Push Docker image to Docker Hub
      run: docker tag reset-password-microservice your-dockerhub-user/reset-password-microservice && docker push your-dockerhub-user/reset-password-microservice
