name: Reset Password Microservice Deployment

on:
  push:
    branches:
      - test
    paths:
      - 'reset-password-microservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        cd reset-password-microservice
        npm install

    - name: Run Tests
      run: |
        cd reset-password-microservice
        npm test

    - name: Build Docker Image
      run: |
        cd reset-password-microservice
        docker build -t reset-password-microservice .

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag reset-password-microservice myrepo/reset-password-microservice:latest
        docker push myrepo/reset-password-microservice:latest
